import 'package:flutter/material.dart';
import 'package:flutterapp/xapapp/generatediphone82widget/generated/GeneratedGOODWidget.dart';
import 'package:flutterapp/xapapp/generatediphone82widget/generated/GeneratedNowXayedwillLiveanotherdayWidget.dart';
import 'package:flutterapp/xapapp/generatediphone82widget/generated/GeneratedAlhamdullilahWidget.dart';

/* Frame iPhone 8 - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone82Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIPhone84Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 1, 132, 253),
                  ),
                ),
                Positioned(
                  left: 44.0,
                  top: 98.0,
                  right: null,
                  bottom: null,
                  width: 266.0,
                  height: 118.0,
                  child: GeneratedGOODWidget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 277.0,
                  right: null,
                  bottom: null,
                  width: 291.0,
                  height: 61.0,
                  child: GeneratedAlhamdullilahWidget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 399.0,
                  right: null,
                  bottom: null,
                  width: 337.0,
                  height: 164.0,
                  child: GeneratedNowXayedwillLiveanotherdayWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
