import 'package:flutter/material.dart';
import 'package:flutterapp/xapapp/generatediphone83widget/generated/GeneratedDrrrrrrdrrrrrrdrrrrrrtahWidget.dart';
import 'package:flutterapp/xapapp/generatediphone83widget/generated/GeneratedDrumrollPleaseWidget.dart';

/* Frame iPhone 8 - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone83Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIPhone82Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 253, 33, 33),
                  ),
                ),
                Positioned(
                  left: 69.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 243.0,
                  height: 155.0,
                  child: GeneratedDrumrollPleaseWidget(),
                ),
                Positioned(
                  left: 104.0,
                  top: 333.0,
                  right: null,
                  bottom: null,
                  width: 172.0,
                  height: 380.0,
                  child: GeneratedDrrrrrrdrrrrrrdrrrrrrtahWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
