import 'package:flutter/material.dart';
import 'package:flutterapp/xapapp/generatediphone81widget/generated/GeneratedIfyouareseeingthiseverythingwentWidget.dart';
import 'package:flutterapp/xapapp/generatediphone81widget/generated/GeneratedImage1Widget.dart';

/* Frame iPhone 8 - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone81Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIPhone83Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 1, 253, 208),
                  ),
                ),
                Positioned(
                  left: 13.0,
                  top: 48.0,
                  right: null,
                  bottom: null,
                  width: 351.0,
                  height: 170.0,
                  child: GeneratedIfyouareseeingthiseverythingwentWidget(),
                ),
                Positioned(
                  left: 13.0,
                  top: 245.0,
                  right: null,
                  bottom: null,
                  width: 349.0,
                  height: 285.0,
                  child: GeneratedImage1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
