import 'package:flutter/material.dart';
import 'package:flutterapp/xapapp/generatediphone84widget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/xapapp/generatediphone84widget/generated/GeneratedShaboskiwillcomebackinshallahinthemeanwhilewehaveshabos.dart';

/* Frame iPhone 8 - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone84Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -98.0,
                right: null,
                bottom: null,
                width: 595.0,
                height: 457.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 170.0,
                child:
                    GeneratedShaboskiwillcomebackinshallahinthemeanwhilewehaveshabos(),
              )
            ]),
      ),
    ));
  }
}
